# Generated by Django 3.2.4 on 2021-06-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamupp', '0003_group_project_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
