# Generated by Django 3.2.4 on 2021-06-21 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamupp', '0004_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='user1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='teamupp.teamuppuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
