# Generated by Django 3.2.4 on 2021-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamupp', '0005_auto_20210621_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='week',
        ),
        migrations.AddField(
            model_name='week',
            name='groups',
            field=models.ManyToManyField(to='teamupp.Group'),
        ),
    ]
