name: Testing

on: [push]

jobs:
  unit-tests: 
      name: Unit testing
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Unit Tests
            uses: actions/setup-python@v2
            with:
                python-version: 3.8
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install flake8 pytest
                pip install -r requirements.txt
          - name: Run Tests
            run: pytest app/tests/
  ui-testing:
    name: UI Tests
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres
        env:
          POSTGRES_DB: teamup-test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
          - uses: actions/checkout@v2
          - name: Run Server
            run: docker-compose up -d
          - name: Cypress running
            uses: actions/setup-node@v2
          - name: Install
            run: cd ui-tests/; npm i
          - name: Run
            run: cd ui-tests/; $(npm bin)/cypress run

