name: Testing

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit Tests
      run: docker-compose -d
      run: docker exec -it teamup_web pytest --cov=. --cov-report html app/tests/
    - name: Cypress Tests
      run: docker-compose -d
      run: cd ui-tests/; npm i && $(npm bin)/cypress run
